### ISSUE TITLE
LSP Config

### ISSUE THREAD

**Issue by benjamin-kirkbride** [cxw42/toolconfig-core-py#5]
Is configuring Language Servers in scope for toolconfig? If so, can I get an example of how that might look?

**Comment by cxw42** [comment]
Toolconfig is use-case agnostic, restricted only by the fact that settings are determined per file path.  Therefore, I don't see any reason why you couldn't configure a language server in a toolconfig file.

However, I have never actually used any language servers!  Therefore, I cannot give an example.  Do you have an example or link of the way it's currently done?

**Comment by benjamin-kirkbride** [comment]
Here is the documentation for it (including an example for EditorConfig, which is interesting): 
https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#workspace_configuration

I am not an expert on EditorConfig, nor LSP, but given that EditorConfig is called out by name and ToolConfig will not be a radical change in paradigm, seems like it should be possible?

**Comment by cxw42** [comment]
Took a glance through it --- looks like `workspace/configuration` might be an arbitrary key-value store, in which case using TC as a backend would be no problem!

**Comment by benjamin-kirkbride** [comment]
Yes, that was my conclusion as well. Awesome!
